apiVersion: apps/v1 
kind: Deployment
metadata:
  name: knowledgebase-api
  labels:
    app: knowledgebase-api 
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: knowledgebase-api
  template:
    metadata:
      labels:
        app: knowledgebase-api                              
    spec:
      containers:
      - name: knowledgebase-api 
        image: visualbean/knowledgebase:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 3000
        envFrom:
          - secretRef:
              name: mysql-secret
      
